### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by torstenzenk** [nextcloud/integration_mattermost#2]
Hi,
thank you for your work to integrate mattermost. I have manually downloaded intergration_mattermost-master.zip, unzipped to the apps folder and renamed it to integration_mattermost. It shows up in the nextcloud apps-list and i activated it there. Now i ask myself: HOW do i set it up to connect with my MM-Server?

Best
Torsten

**Comment by torstenzenk** [comment]
In the settings under index.php/settings/user/connected-accounts there is nothing as you can see in the screenshot. 
![grafik](https://user-images.githubusercontent.com/11678736/186739538-d96094a8-8da0-4f34-874d-af31cbc11c57.png)

Can you please write down how exactly your bridge is set up inluding screenshots?

**Comment by eneiluj** [comment]
Thanks for the interest. The app is still under development. After the first release, it will be a one click install like any other app.

If you really wanna try it before the release, install the latest nightly. Instead of downloading the sources, download the nightly: https://github.com/eneiluj/integration_mattermost/releases/download/v1.0.0-8-nightly/integration_mattermost-1.0.0-8-nightly.tar.gz

**Comment by kyteinsky** [comment]
This issue is now stale since the app has been released and the setup instructions are present in the [readme file](../blob/main/README.md).
